import { Avatar } from "@/components/ui/avatar";
import { Application } from "../../types/applications.types";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { BrainCircuit } from "lucide-react";
import { Knob } from "@/components/common/Knob";
import { Badge } from "@/components/ui/badge";
import { cn } from "@/lib/utils";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { AlertCircle } from "lucide-react";
import { useIsMobile } from "@/hooks/useMobile";
import { useApplicationsActions } from "../../hooks/useApplicationsActions";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";

interface SmartScreeningResultsCardProps {
  application: Application;
  refetch?: () => Promise<void>;
}

export function SmartScreeningResultsCard({
  application,
  refetch,
}: SmartScreeningResultsCardProps) {
  const isMobile = useIsMobile();
  const { runSmartScreening, loading } = useApplicationsActions();

  async function handleSmartScreeningRunning() {
    await runSmartScreening(application.id);

    if (refetch) {
      await refetch();
    }
  }

  return (
    <Card className="col-span-3 gap-4 shadow-none">
      <CardHeader className="flex items-center justify-between">
        <div className="flex items-center gap-4">
          <Avatar className="bg-accent flex items-center p-2 size-10">
            <BrainCircuit className="h-6 w-6" />
          </Avatar>
          <div className="space-y-1">
            <CardTitle>Smart Screening Results</CardTitle>
            <CardDescription>
              View the smart screening results generated by AI for the
              candidate.
            </CardDescription>
          </div>
        </div>
        {!application.aiScore && (
          <Button variant="outline" onClick={handleSmartScreeningRunning}>
            Run Smart Screening
          </Button>
        )}
      </CardHeader>

      {application.aiScore && (
        <CardContent className="space-y-2 grid grid-cols-1 lg:grid-cols-3 animate-in fade-in duration-500 mt-5">
          <div className="col-span-1 h-full flex justify-center items-center mb-10">
            <Knob
              value={application.aiScore || 0}
              size={isMobile ? 120 : 150}
              strokeWidth={isMobile ? 10 : 14}
            />
          </div>

          <div className="col-span-1 lg:col-span-2 space-y-4 text-sm border-s-0 ps-0 border-t pt-6 lg:border-t-0 lg:pt-0 lg:border-s lg:ps-6">
            <DataRow label="Score" value={`${application.aiScore}/100`} />
            <DataRow
              label="AI Summary"
              value={application.aiSummary}
              isLongText
            />
            <DataRow
              label="Recommendation"
              value={<DecisionBadge decision={application.aiDecision as any} />}
            />
          </div>
        </CardContent>
      )}

      {!application.aiScore && !loading && (
        <CardContent className="mt-4">
          <Alert>
            <AlertCircle className="h-4 w-4" />
            <AlertDescription>
              No smart screening results available for this candidate.
            </AlertDescription>
          </Alert>
        </CardContent>
      )}

      {loading && (
        <CardContent className="p-3 flex justify-center items-center">
          <Spinner className="size-8" />
        </CardContent>
      )}
    </Card>
  );
}

function DataRow({
  label,
  value,
  isLongText = false,
}: {
  label: string;
  value: React.ReactNode;
  isLongText?: boolean;
}) {
  return (
    <div className="grid grid-cols-3 gap-4">
      <dt className="text-muted-foreground font-medium">{label}</dt>
      <dd
        className={cn(
          "col-span-2 text-foreground leading-relaxed",
          isLongText ? "text-xs md:text-sm italic" : "font-semibold",
        )}
      >
        {value || "N/A"}
      </dd>
    </div>
  );
}

function DecisionBadge({
  decision,
}: {
  decision: "Reject" | "Move Forward" | "Needs Review";
}) {
  const variants = {
    "Move Forward":
      "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
    Reject: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
    "Needs Review":
      "bg-yellow-100 text-yellow-700 dark:bg-yellow-900/30 dark:text-yellow-400",
  };

  const style = variants[decision] || "bg-gray-100 text-gray-700";

  return (
    <Badge
      className={cn(
        "inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-bold",
        style,
      )}
    >
      {decision}
    </Badge>
  );
}

